---
title: "Earthquake Dashboard: All Earthquakes in Past 7 Days"
author: "<span>Created by <a href='https://zehuiyin.github.io/' target='_blank' style='color: white;'>Zehui Yin</a></span>"
date: "Updated: `r Sys.Date()`"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    theme:
      version: 5
      bootswatch: lux
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(jsonlite)
library(sf)
library(stringr)
library(DT)
library(lubridate)

earthquake <- data.frame(mag = NA,
                         place = NA,
                         time = NA,
                         type = NA,
                         color = NA,
                         title = NA,
                         url = NA,
                         long = NA,
                         lat = NA)

df <- read_json("https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_week.geojson")
df <- df$features
j = 1

for (i in df) {
  earthquake[j, "mag"] <- i$properties$mag
  earthquake[j, "place"] <- i$properties$place
  earthquake[j, "url"] <- i$properties$url
  earthquake[j, "type"] <- i$properties$type
  earthquake[j, "time"] <- as_datetime(i$properties$time/1000)
  
  if (i$properties$type == "earthquake") {
    earthquake[j, "color"] <- "#377eb8"
  } else if (i$properties$type == "quarry blast") {
    earthquake[j, "color"] <- "#e41a1c"
  } else if (i$properties$type == "explosion") {
    earthquake[j, "color"] <- "#ff7f00"
  } else {
    earthquake[j, "color"] <- "#4daf4a"
  }
  
  earthquake[j, "title"] <- i$properties$title
  earthquake[j, "long"] <- i$geometry$coordinates[[1]]
  earthquake[j, "lat"] <- i$geometry$coordinates[[2]]
  j <- j + 1
}

earthquake <- st_as_sf(earthquake, coords = c("long", "lat"), crs = 4326)
```

Row {data-height=300}
-------------------------------------

### Description {data-width=400}

This dashboard visualizes the location and magnitude of all the earthquakes that
occurred in the past week. The data is sourced from the USGS, which provides 
real-time GeoJSON feeds of seismic events around the world. Please note that 
times are expressed in UTC (Coordinated Universal Time).

### Number of Earthquakes {data-width=200}

```{r}
earthquake_count <- nrow(earthquake[earthquake$type == "earthquake",])
valueBox(earthquake_count, icon = "fa-house-crack")
```

### Number of Explosions {data-width=200}

```{r}
explosion_count <- nrow(earthquake[earthquake$type == "explosion",])
valueBox(explosion_count, icon = "fa-explosion")
```

### Number of Quarry Blasts {data-width=200}

```{r}
quarry_blast_count <- nrow(earthquake[earthquake$type == "quarry blast",])
valueBox(quarry_blast_count, icon = "fa-hill-rockslide")
```

Row {data-height=1000}
-------------------------------------

### Earthquake Map {data-width=600}

```{r}
# schema()

plot_ly() %>%
  add_trace(
    type = "scattermapbox",
    lon = st_coordinates(earthquake[which(earthquake$type == "earthquake"),])[,1],
    lat = st_coordinates(earthquake[which(earthquake$type == "earthquake"),])[,2],
    mode = "markers",
    name = "Earthquakes",
    marker = list(
      size = earthquake[which(earthquake$type == "earthquake"),]$mag*5,
      color = earthquake[which(earthquake$type == "earthquake"),]$color
    ),
    hovertext = paste0("Earthquake Magnitude Scales: ", earthquake[which(earthquake$type == "earthquake"),]$mag, "\n",
                       "Place: ", earthquake[which(earthquake$type == "earthquake"),]$place, "\n",
                       "Type: ", earthquake[which(earthquake$type == "earthquake"),]$type, "\n",
                       "URL: ", earthquake[which(earthquake$type == "earthquake"),]$url)
  ) %>%
  add_trace(
    type = "scattermapbox",
    lon = st_coordinates(earthquake[which(earthquake$type == "explosion"),])[,1],
    lat = st_coordinates(earthquake[which(earthquake$type == "explosion"),])[,2],
    mode = "markers",
    name = "Explosions",
    marker = list(
      size = earthquake[which(earthquake$type == "explosion"),]$mag*5,
      color = earthquake[which(earthquake$type == "explosion"),]$color
    ),
    hovertext = paste0("Earthquake Magnitude Scales: ", earthquake[which(earthquake$type == "explosion"),]$mag, "\n",
                       "Place: ", earthquake[which(earthquake$type == "explosion"),]$place, "\n",
                       "Type: ", earthquake[which(earthquake$type == "explosion"),]$type, "\n",
                       "URL: ", earthquake[which(earthquake$type == "explosion"),]$url)
  ) %>%
  add_trace(
    type = "scattermapbox",
    lon = st_coordinates(earthquake[which(earthquake$type == "quarry blast"),])[,1],
    lat = st_coordinates(earthquake[which(earthquake$type == "quarry blast"),])[,2],
    mode = "markers",
    name = "Quarry Blasts",
    marker = list(
      size = earthquake[which(earthquake$type == "quarry blast"),]$mag*5,
      color = earthquake[which(earthquake$type == "quarry blast"),]$color
    ),
    hovertext = paste0("Earthquake Magnitude Scales: ", earthquake[which(earthquake$type == "quarry blast"),]$mag, "\n",
                       "Place: ", earthquake[which(earthquake$type == "quarry blast"),]$place, "\n",
                       "Type: ", earthquake[which(earthquake$type == "quarry blast"),]$type, "\n",
                       "URL: ", earthquake[which(earthquake$type == "quarry blast"),]$url)
  ) %>%
  add_trace(
    type = "scattermapbox",
    lon = st_coordinates(earthquake[which(!earthquake$type %in% c("earthquake", "explosion", "quarry blast")),])[,1],
    lat = st_coordinates(earthquake[which(!earthquake$type %in% c("earthquake", "explosion", "quarry blast")),])[,2],
    mode = "markers",
    name = "Others",
    marker = list(
      size = earthquake[which(!earthquake$type %in% c("earthquake", "explosion", "quarry blast")),]$mag*5,
      color = earthquake[which(!earthquake$type %in% c("earthquake", "explosion", "quarry blast")),]$color
    ),
    hovertext = paste0("Earthquake Magnitude Scales: ", earthquake[which(!earthquake$type %in% c("earthquake", "explosion", "quarry blast")),]$mag, "\n",
                       "Place: ", earthquake[which(!earthquake$type %in% c("earthquake", "explosion", "quarry blast")),]$place, "\n",
                       "Type: ", earthquake[which(!earthquake$type %in% c("earthquake", "explosion", "quarry blast")),]$type, "\n",
                       "URL: ", earthquake[which(!earthquake$type %in% c("earthquake", "explosion", "quarry blast")),]$url)
  ) %>%
  layout(
    mapbox = list(
      style = "open-street-map",
      zoom = 4,
      center = list(lon = -98.58, lat = 39.82)
    ),
    legend= list(itemsizing = "constant",
                 title = list(text = "Type")
                 )
  ) %>%
  config(
    toImageButtonOptions = list(
      format = "svg", 
      width = NULL, 
      height = NULL
    )
  )
```

### Earthquake Data {data-width=300}

```{r}
st_drop_geometry(earthquake)[, colnames(st_drop_geometry(earthquake)) != "color"] |>
  datatable()
```
